FROM ghcr.io/pkegg/port-builder:main

RUN apt-get update \
    && apt-get install -y libgtk-3-dev \
                          python3-protobuf \
                          protobuf-compiler \
                          libsdl2-image-dev \
                          libsdl2-mixer-dev