FROM ghcr.io/pkegg/port-builder:main

RUN apt-get update \
    && apt install -y libssl-dev \
                      libopus-dev \
                      libasound2-dev \
                      libudev-dev \
                      libavahi-client-dev \
                      libcurl4-openssl-dev \
                      libevdev-dev \
                      libexpat1-dev \
                      libpulse-dev \
                      uuid-dev \
                      libavcodec-dev \
                      libavutil-dev \
                      libva-dev \
                      libvdpau-dev \
                      libcec-dev \
                      libp8-platform-dev
